### ISSUE TITLE
AWS init not working

### ISSUE THREAD

**Issue by ingenthr** [couchbaselabs/cbdinocluster#8]
```
Would you like to enable AWS? [Y/n]: 
What AWS region should we use? [us-west-2]: 
Failed to execute command (list instances) with AWS credentials: operation error EC2: DescribeInstances, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded
Would you like to enable AWS? [y/N]: 
```

**Comment by brett19** [comment]
Closing this as wont-fix.  I forgot we switched to a model where we use the credentials directly from the AWS SDK (meaning you need to setup your local environment to work with the AWS cli).  If your local environment would not allow you to use the AWS cli, it also will not allow you to enable it inside of dinocluster, since it would fail anyways.,
